// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PropertyChanged;

namespace FollwItPortable.Model
{
    [ImplementPropertyChanged]
    public class FollwItOnlineChange
    {
        [JsonProperty("item_type")]
        public string ItemType { get; set; }

        [JsonProperty("server_time")]
        public string ServerTime { get; set; }

        [JsonProperty("movie_id")]
        public int? MovieId { get; set; }

        [JsonProperty("rating")]
        public int? Rating { get; set; }

        [JsonProperty("watched")]
        public bool? Watched { get; set; }

        [JsonProperty("new_movie_id")]
        public int? NewMovieId { get; set; }

        [JsonProperty("series_id")]
        public int? SeriesId { get; set; }

        [JsonProperty("tvdb_series_id")]
        public int? TvdbSeriesId { get; set; }

        [JsonProperty("episode_id")]
        public int? EpisodeId { get; set; }
    }
}
